blacklist: []
build_space: ../build/repo
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=RelWithDebInfo
devel_layout: linked
devel_space: ../devel/repo
extend_path: ../devel/deps
install: false
install_space: ../install/repo
isolate_install: false
jobs_args: []
log_space: ../logs/repo
make_args: []
source_space: .
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
